theme = "hyde"
languageCode = "en-us"
baseurl = "rfp"
title = "Reiki for Peace &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;يكي للسلام"
SectionPagesMenu = "main"
[params]
themeColor = "theme-base-0e"

ShowDatesOnPosts = false



# Menu links that appear on the left sidebar
  [[menu.main]]
  name = "Mission Statement"
  url = "/pages/mission-statement/"
  weight = 5

[[menu.main]]
  name = "What is Reiki"
  identifier = "whatisreiki"
  url = "/pages/"
  weight = 10

[[menu.main]]
  name = "Reiki"
  parent = "whatisreiki"
  url = "/pages/reiki/"
  weight = 10

[[menu.main]]
  name = "How Reiki Works"
  parent = "whatisreiki"
  url = "/pages/how-reiki-works/"
  weight = 20

[[menu.main]]
  name = "How to get Reiki"
  parent = "whatisreiki"
  url = "/pages/how-to-get-reiki/"
  weight = 30

[[menu.main]]
  name = "First Degree Reiki Course"
  parent = "whatisreiki"
  url = "/pages/first-degree-reiki-course/"
  weight = 40